language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

env:
    - CODECLIMATE_REPO_TOKEN=356c3e482b7860030a8db4df0c2512030da22c4d1f145e7ff140ad287764d13f

before_script:
    - composer self-update

install: travis_retry composer install --no-interaction --prefer-source

script: 
    - phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=356c3e482b7860030a8db4df0c2512030da22c4d1f145e7ff140ad287764d13f ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
  
notifications:
  email: false