<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-22 at 15:26:46.
 */
class HtpasswdGeneratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HtpasswdGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HtpasswdGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HtpasswdGenerator::add
     * @group production
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtpasswdGenerator::delete
     * @group production
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HtpasswdGenerator::isValid
     * @group validation
     */
    public function testIsValid() {
        $this->object->setUser("testuser1", '$apr1$70crho1l$tuUp8v81nAPPbIMkAOehn1');
        $this->assertEquals(true, $this->object->isValid("testuser1", "123456"));
    }

    /**
     * @group validation
     */
    public function testHelper() {
        $arr = $this->object->getUsers();
        $this->assertEquals(true, is_array($arr));

        $this->object->clearUsers();
        $this->assertEquals(0, count($this->object->getUsers()));

        $arr = $this->object->setUser("testuser1", '$apr1$70crho1l$tuUp8v81nAPPbIMkAOehn1');
        $this->assertEquals(1, count($this->object->getUsers()));
    }

}
